# Generated by Django 5.2.16 on 2026-07-14 02:41

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0002_answeroption_unique_option_order_per_question_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(db_index=True, max_length=6, unique=True, verbose_name='PIN')),
                ('status', models.CharField(choices=[('waiting', 'Sala de espera'), ('question', 'Pregunta activa'), ('results', 'Resultados'), ('finished', 'Finalizada')], db_index=True, default='waiting', max_length=12, verbose_name='Estado')),
                ('question_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Inicio de pregunta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_games', to='quizzes.question', verbose_name='Pregunta actual')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_games', to=settings.AUTH_USER_MODEL, verbose_name='Docente anfitrión')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_sessions', to='quizzes.quiz', verbose_name='Cuestionario')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30, verbose_name='Apodo')),
                ('session_identifier', models.CharField(max_length=40, verbose_name='Identificador de sesión')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Puntaje acumulado')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='livegames.gamesession', verbose_name='Partida')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['-score', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(editable=False, verbose_name='Correcta')),
                ('response_time_ms', models.PositiveIntegerField(editable=False, verbose_name='Tiempo de respuesta (ms)')),
                ('points_earned', models.PositiveIntegerField(default=0, editable=False, verbose_name='Puntos obtenidos')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de respuesta')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='livegames.participant', verbose_name='Participante')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_answers', to='quizzes.question', verbose_name='Pregunta')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_answers', to='quizzes.answeroption', verbose_name='Alternativa seleccionada')),
            ],
            options={
                'verbose_name': 'Respuesta de participante',
                'verbose_name_plural': 'Respuestas de participantes',
                'ordering': ['answered_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nickname'), models.F('game'), name='unique_nickname_ci_per_game'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('game', 'session_identifier'), name='unique_session_per_game'),
        ),
        migrations.AddConstraint(
            model_name='participantanswer',
            constraint=models.UniqueConstraint(fields=('participant', 'question'), name='unique_answer_per_participant_question'),
        ),
    ]
