# Generated by Django 5.2.16 on 2026-07-14 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livegames', '0001_initial'),
        ('quizzes', '0003_answeroption_match_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantanswer',
            name='structured_answer',
            field=models.JSONField(blank=True, default=dict, verbose_name='Respuesta estructurada'),
        ),
        migrations.AddField(
            model_name='participantanswer',
            name='text_answer',
            field=models.TextField(blank=True, verbose_name='Respuesta de texto'),
        ),
        migrations.AlterField(
            model_name='participantanswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participant_answers', to='quizzes.answeroption', verbose_name='Alternativa seleccionada'),
        ),
    ]
