# Generated by Django 5.2.16 on 2026-07-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livegames', '0002_participantanswer_structured_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='projection_mode',
            field=models.BooleanField(default=False, help_text='Oculta soluciones, estadísticas y clasificaciones en la pantalla en vivo del docente.', verbose_name='Modo proyección'),
        ),
    ]
