# Generated by Django 5.2.16 on 2026-07-14 04:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livegames', '0003_gamesession_projection_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('category', models.CharField(choices=[('animal', 'Animales'), ('object', 'Objetos'), ('character', 'Personajes')], db_index=True, max_length=12, verbose_name='Categoría')),
                ('symbol', models.CharField(max_length=12, verbose_name='Símbolo')),
                ('background_color', models.CharField(default='#6D28D9', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Usa un color hexadecimal, por ejemplo #6D28D9.')], verbose_name='Color de fondo')),
                ('image', models.ImageField(blank=True, upload_to='avatars/%Y/%m/', verbose_name='Imagen personalizada')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Disponible')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatares',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='avatar',
            field=models.ForeignKey(blank=True, help_text='Puede estar vacío únicamente en participantes históricos creados antes del catálogo de avatares.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='livegames.avatar', verbose_name='Avatar'),
        ),
    ]
