services:
  - type: web
    name: examplay
    runtime: python
    buildCommand: bash build.sh
    startCommand: daphne -b 0.0.0.0 -p $PORT config.asgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.1
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
