# Generated by Django 5.2.16 on 2026-07-14 02:41

from django.db import migrations, models


def normalize_legacy_orders(apps, schema_editor):
    Question = apps.get_model("quizzes", "Question")
    AnswerOption = apps.get_model("quizzes", "AnswerOption")
    for quiz_id in Question.objects.values_list("quiz_id", flat=True).distinct():
        for order, question in enumerate(Question.objects.filter(quiz_id=quiz_id).order_by("order", "id"), 1):
            Question.objects.filter(pk=question.pk).update(order=order)
    for question_id in AnswerOption.objects.values_list("question_id", flat=True).distinct():
        for order, option in enumerate(AnswerOption.objects.filter(question_id=question_id).order_by("order", "id"), 1):
            AnswerOption.objects.filter(pk=option.pk).update(order=order)


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(normalize_legacy_orders, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='answeroption',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='unique_option_order_per_question'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('quiz', 'order'), name='unique_question_order_per_quiz'),
        ),
    ]
