# Generated by Django 5.2.16 on 2026-07-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_answeroption_unique_option_order_per_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='match_text',
            field=models.CharField(blank=True, max_length=300, verbose_name='Elemento relacionado'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_case_sensitive',
            field=models.BooleanField(default=False, verbose_name='Distinguir mayúsculas en respuesta corta'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Opción múltiple'), ('true_false', 'Verdadero o falso'), ('short_answer', 'Respuesta corta'), ('ordering', 'Ordenamiento'), ('matching', 'Relacionar columnas')], db_index=True, default='multiple_choice', max_length=24, verbose_name='Tipo de pregunta'),
        ),
    ]
